#!/usr/bin/python
from Base_Model.Base_model_detection import Base_Model
import cv2
import numpy as np
import os

dataset = "mp_data"
actions = ['encantado']
capture = cv2.VideoCapture(2, cv2.CAP_DSHOW)

detect = Base_Model(complex=2)
detect.Create_Rutes(dataset, actions)

with detect.holistic_model as holistic:
    for action in actions:
        for sequence in range(detect.num_sequences):
            for frame_num in range(detect.sequence_length):
                success, frame = capture.read()
                image, results = detect.mediapipe_detection(frame, holistic)

                detect.draw_landmarks(image, results)

                image = cv2.flip(image, 1)
                if frame_num == 0:
                    # texto
                    detect.draw_text(frame_num, image, action, sequence)
                    cv2.imshow('MediaPipe Feed', image)
                    cv2.waitKey(2000)
                else:
                    # texto
                    detect.draw_text(frame_num, image, action, sequence)
                    cv2.imshow('MediaPipe Feed', image)

                keypoints = detect.extract_keypoints(results)
                npy_path = os.path.join(detect.DATA_PATH, action, str(sequence), str(frame_num))
                np.save(npy_path, keypoints)

                if cv2.waitKey(10) & 0xFF == 27:
                    exit(0)

    capture.release()
    cv2.destroyAllWindows()